// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpotMapApi.Data;

#nullable disable

namespace SpotMapApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250330092634_AddMarkersRatingsFeature")]
    partial class AddMarkersRatingsFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpotMapApi.Models.Entities.Marker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Markers");
                });

            modelBuilder.Entity("SpotMapApi.Models.Entities.MarkerImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarkerId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MarkerId");

                    b.HasIndex("UserId");

                    b.ToTable("MarkerImages");
                });

            modelBuilder.Entity("SpotMapApi.Models.Entities.MarkerRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MarkerId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarkerId");

                    b.HasIndex("UserId", "MarkerId")
                        .IsUnique();

                    b.ToTable("MarkerRatings");
                });

            modelBuilder.Entity("SpotMapApi.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SpotMapApi.Models.Entities.Marker", b =>
                {
                    b.HasOne("SpotMapApi.Models.Entities.User", "User")
                        .WithMany("Markers")
                        .HasForeignKey("UserId");

                    b.OwnsOne("SpotMapApi.Models.Entities.Coordinates", "Position", b1 =>
                        {
                            b1.Property<int>("MarkerId")
                                .HasColumnType("int");

                            b1.Property<double>("Lat")
                                .HasColumnType("float");

                            b1.Property<double>("Lng")
                                .HasColumnType("float");

                            b1.HasKey("MarkerId");

                            b1.ToTable("Markers");

                            b1.WithOwner()
                                .HasForeignKey("MarkerId");
                        });

                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpotMapApi.Models.Entities.MarkerImage", b =>
                {
                    b.HasOne("SpotMapApi.Models.Entities.Marker", "Marker")
                        .WithMany("AdditionalImages")
                        .HasForeignKey("MarkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotMapApi.Models.Entities.User", "User")
                        .WithMany("Images")
                        .HasForeignKey("UserId");

                    b.Navigation("Marker");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpotMapApi.Models.Entities.MarkerRating", b =>
                {
                    b.HasOne("SpotMapApi.Models.Entities.Marker", "Marker")
                        .WithMany("Ratings")
                        .HasForeignKey("MarkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotMapApi.Models.Entities.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marker");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpotMapApi.Models.Entities.Marker", b =>
                {
                    b.Navigation("AdditionalImages");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("SpotMapApi.Models.Entities.User", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Markers");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
